### ISSUE TITLE
Typescript declaration file / typings npm package: @types/save-as

### ISSUE THREAD

**Issue by fedorbirjukov** [cchamberlain/save-as#1]
At least, doing "export default saveAs" is not a good idea: it makes you call module.default() instead of module.saveAs().

**Comment by cchamberlain** [comment]
Thanks for opening. I've used some flow but typescript not so much. I disagree with you on whether it is a good idea: It is currently optimized towards the future of JavaScript (ES2015+), not typescript. Since the library only does one thing, it made sense to make that one thing the default export.

In ES2015+:

`import saveAs from 'save-as'`

Removing the default export would cause a major breaking API change. If it helps your use case however, I would be willing to add a saveAs export (non-default).

**Comment by fedorbirjukov** [comment]
Thanks for replying. Good point about the future of JavaScript. I think a non-default export would be of great help for those who use TypeScript.

If you just add
```
exports.saveAs = saveAs;
```

Then it is possible to write a TypeScript declaration for you module, like:
```
declare module 'save-as' {
    function saveAs(data: Blob, filename: string, noAutoBOM?: boolean): void;
}
```

And named import works:
```
import { saveAs } from 'save-as';
function save() {
    let blob = new Blob(['Hello world!'], { type: 'text/plain;charset=utf-8' });
    saveAs(blob, 'newcontrol.txt');
}
```

**Comment by cchamberlain** [comment]
Just published `v0.1.8` with an additional saveAs export, can you give that a try?

**Comment by fedorbirjukov** [comment]
It works. It is incredible you did it so fast, thank you!

**Comment by cchamberlain** [comment]
@fedorbirjukov - NP! Glad it's getting use.

**Comment by EdmondChuiHW** [comment]
Thank you everyone here for coming up with the fix. Just in case anyone else comes across this, here is what did to get it to work with Angular 4 + Typescript + Webpack:

```
const saveAsModule = require("save-as");
…
saveAsModule.saveAs(blob, fileName);
```
